import json
import argparse
from pathlib import Path


def make_arg_parser():
    parser = argparse.ArgumentParser(
        description="Generate a JSON manifest of SAIGE GWAS pipeline outputs for report generation."
    )
    parser.add_argument('--params_json', required=True,
                        help='Path to saige_gwas_params.json generated by the pipeline')
    parser.add_argument('--pheno_summaries', required=True,
                        help='Path to pheno_summaries.csv')
    parser.add_argument('--gwas_summary', required=True,
                        help='Path to saige_gwas_suggestive.csv')
    parser.add_argument('--plots_dir', required=True,
                        help='Directory containing PNG plot files')
    parser.add_argument('--output', default='saige_gwas_manifest.json',
                        help='Output path for the manifest JSON (default: saige_gwas_manifest.json)')
    return parser


def to_list(val):
    """Ensure a value is a list; handle scalars and None."""
    if isinstance(val, list):
        return val
    if val is None:
        return []
    return [val]


def main():
    args = make_arg_parser().parse_args()

    with open(args.params_json) as f:
        params = json.load(f)

    # Read from nested structured JSON (with flat fallback for compatibility)
    cpc = params.get('cohorts_phenotypes_chromosomes', params)
    other = params.get('other_parameters', params)

    cohort_list = to_list(cpc.get('cohort_list', []))
    bin_pheno_list = to_list(cpc.get('bin_pheno_list', []))
    quant_pheno_list = to_list(cpc.get('quant_pheno_list', []))
    survival_pheno_list = to_list(cpc.get('survival_pheno_list', []))
    p_cutoff = other.get('p_cutoff_summarize', 5e-6)
    all_phenos = bin_pheno_list + quant_pheno_list + survival_pheno_list

    plots_dir = Path(args.plots_dir)

    # Pheno-level summary plots: {pheno}.*.png
    pheno_summary_plots = {}
    for pheno in all_phenos:
        plots = sorted(plots_dir.glob(f'{pheno}.*.png'))
        if plots:
            pheno_summary_plots[pheno] = [str(p) for p in plots]

    # GWAS plots: {cohort}.{pheno}.manhattan_vertical.png / .qq.png
    gwas_plots = {}
    for cohort in cohort_list:
        gwas_plots[cohort] = {}
        for pheno in all_phenos:
            entry = {}
            manhattan = plots_dir / f'{cohort}.{pheno}.manhattan_vertical.png'
            qq = plots_dir / f'{cohort}.{pheno}.qq.png'
            if manhattan.exists():
                entry['manhattan'] = str(manhattan)
            if qq.exists():
                entry['qq'] = str(qq)
            if entry:
                gwas_plots[cohort][pheno] = entry

    manifest = {
        'cohort_list': cohort_list,
        'bin_pheno_list': bin_pheno_list,
        'quant_pheno_list': quant_pheno_list,
        'survival_pheno_list': survival_pheno_list,
        'p_cutoff_summarize': p_cutoff,
        'gwas_summary_csv': args.gwas_summary,
        'pheno_summaries_csv': args.pheno_summaries,
        'pheno_summary_plots': pheno_summary_plots,
        'gwas_plots': gwas_plots,
        'params': params,
    }

    with open(args.output, 'w') as f:
        json.dump(manifest, f, indent=2)

    print(f"Manifest written to {args.output}")
    print(f"  Cohorts       : {cohort_list}")
    print(f"  Binary phenos : {bin_pheno_list}")
    print(f"  Quant phenos  : {quant_pheno_list}")
    print(f"  Survival phenos: {survival_pheno_list}")
    n_gwas = sum(len(v) for v in gwas_plots.values())
    print(f"  GWAS plot combos: {n_gwas}")


if __name__ == '__main__':
    main()
