import json
import argparse
from pathlib import Path


def make_arg_parser():
    parser = argparse.ArgumentParser(
        description="Generate a JSON manifest of SAIGE ExWAS pipeline outputs for report generation."
    )
    parser.add_argument('--params_json', required=True,
                        help='Path to saige_exwas_params.json generated by the pipeline')
    parser.add_argument('--pheno_summaries', required=True,
                        help='Path to pheno_summaries.csv')
    parser.add_argument('--singles_summary', required=True,
                        help='Path to saige_exwas_suggestive_singles.csv')
    parser.add_argument('--regions_summary', required=True,
                        help='Path to saige_exwas_suggestive_regions.csv')
    parser.add_argument('--plots_dir', required=True,
                        help='Directory containing PNG plot files')
    parser.add_argument('--output', default='saige_exwas_manifest.json',
                        help='Output path for the manifest JSON (default: saige_exwas_manifest.json)')
    return parser


def to_list(val):
    """Ensure a value is a list; handle scalars and None."""
    if isinstance(val, list):
        return val
    if val is None:
        return []
    return [val]


def main():
    args = make_arg_parser().parse_args()

    with open(args.params_json) as f:
        params = json.load(f)

    # Read from nested structured JSON (with flat fallback for compatibility)
    cpc = params.get('cohorts_phenotypes_chromosomes', params)
    other = params.get('other_parameters', params)

    cohort_list = to_list(cpc.get('cohort_list', []))
    bin_pheno_list = to_list(cpc.get('bin_pheno_list', []))
    quant_pheno_list = to_list(cpc.get('quant_pheno_list', []))
    survival_pheno_list = to_list(cpc.get('survival_pheno_list', []))
    p_cutoff = other.get('p_cutoff_summarize', 5e-6)
    all_phenos = bin_pheno_list + quant_pheno_list + survival_pheno_list

    plots_dir = Path(args.plots_dir)

    # Pheno-level summary plots: {pheno}.{plot_type}.png
    pheno_summary_plots = {}
    for pheno in all_phenos:
        plots = sorted(plots_dir.glob(f'{pheno}.*.png'))
        if plots:
            pheno_summary_plots[pheno] = [str(p) for p in plots]

    # Singles plots: {cohort}.{pheno}.singles.manhattan_vertical.png / .singles.qq.png
    singles_plots = {}
    for cohort in cohort_list:
        singles_plots[cohort] = {}
        for pheno in all_phenos:
            entry = {}
            manhattan = plots_dir / f'{cohort}.{pheno}.singles.manhattan_vertical.png'
            qq = plots_dir / f'{cohort}.{pheno}.singles.qq.png'
            if manhattan.exists():
                entry['manhattan'] = str(manhattan)
            if qq.exists():
                entry['qq'] = str(qq)
            if entry:
                singles_plots[cohort][pheno] = entry

    # Regions plots: {cohort}.{pheno}.{combo}.regions.{plot_type}.png
    # combo = e.g. "pLoF.maf0.01" — everything between pheno and ".regions."
    regions_plots = {}
    for cohort in cohort_list:
        regions_plots[cohort] = {}
        for pheno in all_phenos:
            prefix = f'{cohort}.{pheno}.'
            combos = {}
            for png in sorted(plots_dir.glob(f'{cohort}.{pheno}.*.png')):
                stem = png.stem
                if '.singles.' in stem:
                    continue
                if '.regions.' not in stem:
                    continue
                remainder = stem[len(prefix):]          # e.g. pLoF.maf0.01.regions.manhattan
                parts = remainder.split('.regions.')    # ['pLoF.maf0.01', 'manhattan']
                if len(parts) != 2:
                    continue
                combo_key, plot_type = parts[0], parts[1]
                combos.setdefault(combo_key, {})[plot_type] = str(png)
            if combos:
                regions_plots[cohort][pheno] = combos

    manifest = {
        'cohort_list': cohort_list,
        'bin_pheno_list': bin_pheno_list,
        'quant_pheno_list': quant_pheno_list,
        'survival_pheno_list': survival_pheno_list,
        'p_cutoff_summarize': p_cutoff,
        'singles_summary_csv': args.singles_summary,
        'regions_summary_csv': args.regions_summary,
        'pheno_summaries_csv': args.pheno_summaries,
        'pheno_summary_plots': pheno_summary_plots,
        'singles_plots': singles_plots,
        'regions_plots': regions_plots,
        'params': params,
    }

    with open(args.output, 'w') as f:
        json.dump(manifest, f, indent=2)

    print(f"Manifest written to {args.output}")
    print(f"  Cohorts            : {cohort_list}")
    print(f"  Binary phenos      : {bin_pheno_list}")
    print(f"  Quant phenos       : {quant_pheno_list}")
    print(f"  Survival phenos    : {survival_pheno_list}")
    n_singles = sum(len(v) for v in singles_plots.values())
    n_regions = sum(len(v) for v in regions_plots.values())
    print(f"  Singles plot combos: {n_singles}")
    print(f"  Regions plot combos: {n_regions}")


if __name__ == '__main__':
    main()
