name: base
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - adjustText
  - dominate
  - apsw
  - sqlite
  - conda-build
  - bgenix
  - libtiff
